server:
  port: 8882

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: test-feign

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
feign:
  hystrix:
    enabled: true
  okhttp:
    enabled: true
  client:
    config:
      feign-server-b:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true